# Generated by the kanatabar release workflow — do not edit here.
# Source: https://github.com/ibimal/kanatabar/blob/main/packaging/homebrew/kanatabar.rb
cask "kanatabar" do
  version "__VERSION__"
  sha256 "__SHA256__"

  url "https://github.com/ibimal/kanatabar/releases/download/v#{version}/KanataBar-#{version}.pkg"
  name "KanataBar"
  desc "Supervisor and menu bar app for the kanata keyboard remapper"
  homepage "https://github.com/ibimal/kanatabar"

  depends_on macos: :ventura

  pkg "KanataBar-#{version}.pkg"

  # /bin/sh (always present) is the executable, not kanatactl: if the user
  # already ran `sudo kanatactl uninstall` by hand, the binary is gone and a
  # direct reference would make every brew upgrade/reinstall/uninstall fail
  # with "uninstall script does not exist".
  uninstall script:  {
              executable: "/bin/sh",
              args:       [
                "-c",
                "[ -x /usr/local/bin/kanatactl ] && /usr/local/bin/kanatactl uninstall || true",
              ],
              sudo:       true,
            },
            pkgutil: "io.github.ibimal.kanatabar"

  caveats <<~EOS
    KanataBar requires kanata and the Karabiner-DriverKit-VirtualHIDDevice
    driver; the menu bar Setup Assistant walks you through installing both and
    granting the needed permissions.

    KanataBar is not notarized (no paid Apple Developer account — see the
    project README). If macOS blocks it, allow it under System Settings →
    Privacy & Security → "Open Anyway".

    brew upgrade is the only update mechanism; the app never self-updates.
  EOS
end
